
name: CocktailJS

description: Shake your objects and classes with Cocktail!

author: Maximiliano Fierro

username: CocktailJS
repository: cocktail

analytics: UA-39565774-1

docs: {
    version: 0.5.3
}

markdown: redcarpet
permalink: none

safe: true
lsi: false
pygments: true
