
name: CocktailJS

description: Shake your objects and classes with Cocktail!

author: Maximiliano Fierro

username: CocktailJS
repository: Cocktail

analytics: UA-39565774-1

docs: {
	version: 0.4.1
}

markdown: redcarpet
permalink: none

safe: true
lsi: false
pygments: true
